== GTS to WIS2 Gateway

The Executive Council, with resolution 34 (EC-76), endorsed the WMO Information System 2 (WIS2) implementation plan and recognized the importance of establishing a pilot phase to develop the WIS2 infrastructure and begin testing it in order to be ready for a preoperational phase in 2024, and then for the transition starting on 2025. According to the WIS2 implementation plan, the Global Telecommunication System (GTS) will be decommissioned by 2030, and National Meteorological and Hydrological Services NMHSs will use the WIS2 platform for data exchange.

During the transition period, in order to avoid some WIS centres being forced to run both data-sharing frameworks simultaneously WIS2 and GTS, with the challenges associated with maintaining two operational systems for the same purpose, a gateway from GTS to WIS2 is designed, taking into account the time required for Members to migrate to the new systems and minimizing the time a member has to operate both systems in parallel.

=== Purpose

The purpose of the GTS to WIS2 gateway is to enable members who have migrated to WIS2 and have stopped their GTS systems to continue receiving GTS data from WIS2. This gateway also enables users who are not connected to GTS to access GTS data, during the transition phase, from WIS2.

=== GTS to WIS2 Gateway provider

The gateway will be provided by Germany's Deutscher Wetterdienst (DWD). The Japanese Meteorological Agency (JMA) may provide a second gateway for increased sustainability and resilience.
 
=== Technical requirements

* GTS headers SHALL be used in the WIS2 Topic Hierarchy (WTH)
* The TH for GTS data on the Global Cache (GC) SHALL be as follows:
** ``cache/a/wis2/xxg/gts_to_wis2_GC-name/TTAAii``
** e.g for DWD: ``cache/a/wis2/xxg/gts_to_wis2_dwd/TTAAii``
