== GTS to WIS2 Gateway

The Executive Council, with resolution 34 (EC-76), endorsed the WMO Information System 2 (WIS2) implementation plan and recognized the importance of establishing a pilot phase to develop the WIS2 infrastructure and begin testing it in order to be ready for a preoperational phase in 2024, and then for the transition starting on 2025. According to the WIS2 implementation plan, the Global Telecommunication System (GTS) will be decommissioned by 2030, and National Meteorological and Hydrological Services NMHSs will use the WIS2 platform for data exchange.

During the transition period, in order to avoid some WIS centres being forced to run both data-sharing frameworks WIS2 and GTS simultaneously, with the challenges associated with maintaining two operational systems for the same purpose, a gateway from GTS to WIS2 is designed, taking into account the time required for Members to migrate to the new systems and minimizing the time a member has to operate both systems in parallel.

=== Purpose

The purpose of the GTS to WIS2 gateway is to enable members who have migrated to WIS2 and have stopped their GTS systems to continue receiving GTS data from WIS2. This gateway also enables users who are not connected to GTS to access GTS data, during the transition phase, from WIS2. The GTS to WIS2 gateway will forward all the GTS traffic it receives to WIS2, that is each bulletin received on one of its GTS channels will be stored to the HTTP(s) endpoint of the Gateway and a WIS2 Notification Message is generated which points to that bulletin file. The Notification Message is published at the GTS to WIS2 gateway topic.

=== GTS to WIS2 Gateway provider

The gateway will be provided by Germany's Deutscher Wetterdienst (DWD) and the Japan Meteorological Agency (JMA).
 
=== Technical requirements

* GTS headers SHALL be used in the WIS2 Topic Hierarchy (WTH)
* The TH for GTS data on WIS2 SHALL be as follows:
** ``origin/a/wis2/[GC-name]/data/[core|recommended]/T1/T2/A1/A2/ii/CCCC``
** e.g for DWD: ``origin/a/wis2/de-dwd-gts-to-wis2/data/[core|recommended]/T1/T2/A1/A2/ii/CCCC`` and for JMA: ``origin/a/wis2/jp-jma-gts-to-wis2/data/[core|recommended]/T1/T2/A1/A2/ii/CCCC``
* The GTS to WIS2 data is copied on the WIS2 Global Caches if the data is WMO Core Data.
* Each GTS to WIS2 Gateway SHALL maintain a list of TTAAii headers for Core and for Recommended data in order to be able to send the notification to the correct topic. The list is coordinated and shared between the Gateways.
* The data_id for each GTS to WIS2 Gateway SHALL be unique. That is each gateway will choose different data ids for example by adding their centre name reflecting the fact, that GTS bulletins with the same header might be different at the different locations. Therefore there will be two or more different GTS to WIS2 datasets (one for each gateway).
* Example for a valid GTS to WIS2 data id is ``wis2/de-dwd-gts-to-wis2/data/core/W/W/X/X/60/EDZW/WWXX60EDZW200900``
* Data Consumers receiving the GTS data through WIS2 will need to be able to handle duplicates. This is in line with the current practices of handling duplicate messages on the GTS.
* Access to recommended GTS data should be restricted to WMO members.
