== GTS to WIS2 Gateway

=== Purpose

The purpose of the GTS to WIS2 gateway is to enable Members, having migrated to WIS2, to stop their GTS systems while continueing receiving GTS data via WIS2. In addition, this gateway function also enables users who are not connected to GTS to already obtain data originally published on the GTS. The function of GTS to WIS2 gateway is to forward all the GTS traffic received by the Member operating that service, to WIS2, so that data received on its Message Switching System (MSS) will be stored and made available via HTTP(S). A Notification Message is then generated. It is published using the centre-id name defined for this gateway.
 
=== Technical requirements

* A GTS to WIS2 gateway is a DCPC function. All requirements related to WIS2 Nodes are applicable.

* In addition to the standard WIS2 Node specifications, the GTS to WIS2 gateway will: 
** The Topic Hierarchy for GTS data on WIS2 will be:
*** ``origin/a/wis2/{centre-id}/data/[core|recommended]/T1/T2/A1/A2/ii/CCCC``
*** e.g for DWD: ``origin/a/wis2/de-dwd-gts-to-wis2/data/[core|recommended]/T1/T2/A1/A2/ii/CCCC`` and for JMA: ``origin/a/wis2/jp-jma-gts-to-wis2/data/[core|recommended]/T1/T2/A1/A2/ii/CCCC``
** The ``T1/T2/A1/A2/ii/CCCC`` above is derived from the headers of the data received on the GTS.

* The Global Caches will cache data that is being published using ``core`` in the Topic Hierarchy.
* Data Consumers receiving the GTS data through WIS2 will need to be able to handle duplicates. This is consistent with the current practices of handling duplicate messages on the GTS.
* Access to recommended GTS data should be restricted to WMO members.
