== WIS 2.0 implementation Plan
The Executive Council, with resolution 34 (EC-76), endorsed the WMO Information System 2.0 (WIS2) implementation plan and recognized the importance of establishing a pilot phase to develop the WIS2 infrastructure and begin testing it to be ready for a pre-operational phase in 2024, and then for the transition starting on 2025. This plan will be implemented according to the schedule provided in Figure 1. The pilot phase has been completed at the end of 2023, with several countries collaborating in building the WIS 2.0 infrastructure. Each Country had a different role in the WIS 2.0 framework and implemented a specific component. Starting in January 2024, the implementation of WIS 2.0 will enter the pre-operational phase, and the WIS 2.0 services shall be ready to transition to an operational configuration, which is critical to ensure that WIS 2.0 can serve the WMO community operationally from the beginning of 2025.  It’s planned to migrate to WIS2 between 2025 and 2030, with an expected progress rate of up to 90% of migrations. The GTS is planned to be decommissioned by 2033.
