=== 5.3 Management of GTS Abbreviated Headings

The GTS abbreviated headings are described in the Manual on the Global Telecommunication System (WMO-No. 386). In particular the data designators T1T2A1A2ii are defined in Attachement II.5 of this Manual. The GTS abbreviated headings are not required in WIS2 and their use is limited to the exchange of data on the GTS. Starting from WIS2 becoming operational any further evolution of the GTS, including the transmission of new data, will not be permitted. Therefore the Manual on GTS will no longer be updated from 31 December 2024. 
The Weather Reporting (WMO-No. 9) Volume C1 contains the list of meteorological bulletins exchanged on the GTS. There is a requirement for Members to update Volume C1 every time a change in the bulletins takes place, but only a few Members are doing it with regularity and therefore the list is incomplete and is not consistent with the bulletins effectively exchanged on GTS. With the start of the WIS2 operational phase there will not be any change in the list of meteorological bulletins transmitted on GTS, therefore Volume C1 will not be updated any longer from 31 December 2024. 

==== 5.3.1 GTS Headings for ICAO (AFTN)

The attachement II.5 of the Manual on GTS (WMO-No. 386) containing the data designators T1T2A1A2ii currently used for transmission of data on GTS are also used for the same purpose on AFTN by ICAO. There is a requirement for WMO to maintain the data designators for ICAO data transmission purposes. To satisfy this requirement WMO Secretariat will liase with ICAO to allow the addition of new data designators when required by ICAO. The new data designators requested by ICAO will not be published in the Manual on GTS (WMO No. 386), a different mean for their publication will be agreed by WMO and ICAO.
