=== 5.3 Management of GTS abbreviated headings

The GTS abbreviated headings are described in the https://library.wmo.int/idurl/4/35800[_Manual on the Global Telecommunication System_] (WMO-No. 386) (_Manual on GTS_). The data designators T1T2A1A2ii are defined in Attachment II.5 of the Manual on GTS. The GTS abbreviated headings are not required in WIS2, and their use is limited to the exchange of data on the GTS. Once WIS2 becomes operational, any further evolution of the GTS, including the transmission of new data, will not be permitted. Therefore, the Manual on GTS will no longer be updated from 31 December 2024. 
The https://library.wmo.int/idurl/4/55155[_Weather Reporting_] (WMO-No. 9), Volume C1, contains the list of meteorological bulletins exchanged on the GTS. Members are required to update Volume C1 every time a change in the bulletins takes place, however only a few Members are doing so with regularity. The list is therefore incomplete and is not consistent with the bulletins effectively exchanged on GTS. With the start of the WIS2 operational phase, there will not be any change in the list of meteorological bulletins transmitted on GTS, therefore Volume C1 will not be updated any longer from 31 December 2024. 

==== 5.3.1 GTS headings for International Civil Aviation Authority

Attachment II.5 of the Manual on GTS containing the data designators T1T2A1A2ii currently used for transmission of data on GTS are also used for the same purpose on the Aeronautical Fixed Telecommunications Network (AFTN) by the International Civil Aviation Authority (ICAO). There is a requirement for WMO to maintain the data designators for ICAO data transmission purposes. To satisfy this requirement, the WMO Secretariat will liaise with ICAO to allow the addition of new data designators when required by ICAO. The new data designators requested by ICAO will not be published in the Manual on GTS, but rather a different means for their publication will be agreed upon by WMO and ICAO.
