== Management of WIS1 and GTS

=== Maintenance and operation of Message Switching System (MSS)

==== Main Telecommunication Network

With the start of the pre-operational phase of WIS 2.0, the Main Telecommunication Network (MTN), linking together the World Meteorological Centres (WMCs) as well as designated Regional Telecommunication Hubs (RTHs); shall keep their Message Switching Systems (MSS) up and continue to publish data collecting the bulletins from their associated National Meteorological Centres (NMCs) and transmitting them in the appropriate form on the Main Telecommunication Network (MTN), either directly or through the appropriate WMC/RTH in GTS until the transition from GTS to WIS 2.0 is advanced. 

==== Regional Telecommunication Hubs

Regional Telecommunication Hubs (RTHs) shall keep their Message Switching Systems (MSS) up and continue to publish data Collecting the bulletins from their associated National Meteorological Centres (NMCs) and transmitting them in the appropriate form on the Main Telecommunication Network (MTN), either directly or through the appropriate WMC/RTH in GTS until all Members in their area of responsability migrate from GTS to WIS 2.0.

Regional Telecommunication Hubs (RTHs) that have implemented a WIS 2.0 node and all Members in their area of responsibility (AoR) have migrated to WIS 2.0, could decide to turn off their message switching system (MSS). 

They shall liaise with their users and with centres in their AoR and point them to the WIS 2.0 Global Services.

==== National Meteorological Centres

National Meteorological Centres (NMCs) shall operate a WIS 2.0 node to share their data and discovery metadata in WIS 2.0.

NMCs that have implemented a WIS 2.0 node, and published all the data transmitted in the GTS on WIS 2.0 could, if they wish, turn off their GTS system MSS and stop transmitting data in the GTS. 
When NMCs decide to decommission and turn off their GTS system MSS and stop transmitting their data in GTS, they should include the GTS properties in the notification message as described in the WIS 2.0 to GTS gateway technical requirements.

Note: this notification message update will concern only data that are already published in GTS. New data will be published only on WIS 2.0.
