== 	Maintenance and operation of Message Switching System (MSS)
=== Main Telecommunication Network
With the start of the pre-operational phase of WIS2, the Main Telecommunication Network (MTN), linking together the World Meteorological Centres (WMCs) as well as designated Regional Telecommunication Hubs (RTHs); shall keep their Message Switching Systems (MSS) up and continue to publish data Collecting the bulletins from their associated National Meteorological Centres (NMCs) and transmitting them in the appropriate form on the Main Telecommunication Network (MTN), either directly or through the appropriate WMC/RTH in GTS until the transition from GTS to WIS2 is advanced. 

=== Regional Telecommunication Hubs
Regional Telecommunication Hubs (RTHs) shall keep their Message Switching Systems (MSS) up and continue to publish data Collecting the bulletins from their associated National Meteorological Centres (NMCs) and transmitting them in the appropriate form on the Main Telecommunication Network (MTN), either directly or through the appropriate WMC/RTH in GTS until all Members in their area of responsability migrate from GTS to WIS2.
Regional Telecommunication Hubs (RTHs) that have implemented a WIS2 node and all Members in their area of responsibility (AoR) have migrated to WIS2, could decide to turn off their message switching system (MSS). 
They shall liaise with their users and with centers in their AoR and point them to the WIS 2.0 global services.

=== National Meteorological Centres
National Meteorological Centres (NMCs) shall operate a WIS2 node to share their data and discovery metadata in WIS 2.0.
NMCs that have implemented a WIS2 node, and published all the data transmitted in the GTS on WIS2 could, if they wish, turn off their GTS system MSS and stop transmitting data in the GTS. 
When NMCs decide to decommission and turn off their GTS system MSS and stop transmitting their data in GTS, they should include the GTS properties in the notification message as described in the WIS2 to GTS gateway technical requirements.

Note: this notification message update will concern only data that are already published in GTS. New data will be published only on WIS2.

== Management of GTS Abbreviated Headings

=== GTS during the transition phase

* The GTS headers have been managed by volume C1 which has not been updated for several years. 
* The latest version of Volume C1 will be published on the WMO website (TBD). 
* No new GTS header will be allocated during the transition phase. 
* The volume C1 will be decommissioned by December 2024.

=== GTS Headings for ICAO (AFTN)
The management of GTS headings for the International Civil Aviation Organization (ICAO) will be done in collaboration with ICAO.
Whenever a new request is made to add a new CCCC, it will first be checked against the latest ICAO and WMO Secretariat CCCC list to ensure that it is not attributed to any centre, and then the WMO Secretariat will add it and publish it on the dedicated WMO website and inform ICAO about it.
