== Migration from GTS to WIS2

=== Pre-operational and operational phases

==== Definition of pre-operational phase

The objective of the pre-operational phase is to make the transition from the Pilot Phase to the operational phase.

The purpose of this phase is to verify that the WIS 2.0 implementation has been carried out in accordance with the technical specifications of WIS 2.0 and to make the changes approved in the pilot phase in a satisfactory operational manner.

This phase covers all activities related to the installation and integration of the WIS 2.0 components developed during the pilot phase, including the testing activities necessary to verify the integration and proper functioning of data exchange via WIS 2.0.

==== Requirements for the pre-operational phase

During the pilot phase in 2023 the infrastructure of WIS 2.0 was developed and tests to refine the WIS 2.0 technical specifications have been carried out.  The pre-operational phase is the clean-up phase to make the transition to operations.

The following actions are required for a smooth transition:

* software adopted to run a WIS 2.0 Node shall be compliant with WIS 2.0 technical regulations
* WIS 2.0 node details shall be communicated to the WMO Secretariat
* the WIS 2.0 Topic Hierarchy shall be updated to the latest approved version
* All data transmitted in GTS shall be published in WIS 2.0
* Discovery Metadata shall be prepared and published in accordance with the WMO Core Metadata Profile (WCMP2)
* SYNOP core data shall be published hourly (minutely data not required)

==== How to make the transition from the pre-operational to operational phase

The pre-operational phase aims to ensure that all the improvements made during the pilot phase are deployed and tested. During this phase performance tests of all the WIS 2.0 components will be made and relevant adjustments will be completed to be ready for the operation.

Members shall liaise with their users and make the necessary arrangements to meet their needs and point them to the WIS 2.0 global services.

The following actions shall be completed for a smooth transition from the pre-operational to operational phase:

* The latest technical improvements shall be installed and tested before **31 October 2024**.
* Build the skills needed to support the WIS 2.0 operations, which include:
** Infrastructure
** Upgrade management
** Data management
** Customer services support
** Incident management
** Monitoring
* Business continuity and disaster recovery plans must be in place to ensure that, in the event of failure, the business can continue or, in the worst case, recover within the required time scale from any significant disaster. This might include:
** provision for offsite backup 
** Supply of an identical replacement system within a specified time
