== 3.1.1.	Definition of pre-operational phase
The objective of the pre-operational phase is to make the transition from the Pilot Phase to the operational phase.
The purpose of this phase is to verify that the WIS2 implementation has been carried out in accordance with the technical specifications of WIS 2.0 and to make the changes approved in the pilot phase in a satisfactory operational condition.

This phase covers all activities related to the installation and integration of the WIS 2.0 components developed during the pilot phase, including the testing activities necessary to verify the integration and proper functioning of data exchange via WIS 2.0.

== 3.1.2.	How to make the transition from pilot to pre-operational phase
The pilot phase aims to develop the infrastructure of WIS 2.0 and make the tests to refine the WIS 2.0 technical specifications.  The pre-operational phase is the clean-up phase to make the transition to operation.

The following actions are required for a smooth transition:

* The software adopted to run a WIS2 node shall be compliant with WIS 2.0 technical regulations,
*	The WIS2 node details shall be communicated to the WMO Secretariat,
*	The topic Hierarchy shall be updated to the latest version,
*	All the data transmitted in GTS shall be published in WIS2,
*	The Discovery metadata shall be prepared and published in accordance with the WMO Core Metadata Profile (WCMP2).
*	SYNOP core data shall be published hourly, no minute data required.

== 3.1.3.	How to make the transition from pre-operational to operational
The pre-operational phase aims to ensure that all the improvements made during the pilot phase are deployed and tested. During this phase performance tests of all the WIS2 components will be made and relevant adjustments will be completed to be ready for the operation.
Members shall liaise with their users and make the necessary arrangements to meet their needs and point them to the WIS 2.0 global services.
The following actions shall be completed for a smooth transition from pre-operational to operational:

*	The latest technical improvements shall be installed and tested before 31 October 2024.
*	Build the skills needed to support the WIS 2.0 operations, this shall include:
**	Infrastructure
**	Upgrade management
**	Data management
**	Customer services support
**	Incident management
**	Monitoring
*	Business Continuity and Disaster Recovery: 
Plans must be in place to ensure that, in the event of failure, the business can continue or, in the worst case, recover within the required time scale from any significant disaster. This might include:
**	provision for offsite backup 
**	Supply of an identical replacement system within a specified time
