== 3. Principles

The following principles are appropriate for the transition.

**Principle 1**: Each National Meteorological and Hydrological Service (NMHS) will be able to make the migration during the agreed period 2025–2030:

	* NMHSs will migrate between 2025 and 2030 at a time convenient for them. There will not be a simultaneous migration of all
	the WIS centres from WIS1 to WIS2.

_Note: WIS centres are Global Information System Centres (GISCs), Data Collection or Production Centres (DCPCs) and National Centres (NCs)._

**Principle 2**: No GTS data loss during the transition:
	
	* During the pre-operational phase, and in coordination with the regional associations and Global Information System Centres (GISCs), WIS2 infrastructure will be established, in order to avoid data loss during the transition. The aim of this infrastructure is to ensure that data sent on the GTS can be received by a site having migrated to WIS2, and the data, previously sent on the GTS, sent on WIS2, can be received by a site still on the GTS.

**Principle 3**: Each WIS centre will decide when to decommission WIS1 and GTS:
	
	* Decommissioning WIS1 and GTS services will be the decision of each National Centre (NC), Data Collection and Production Centre (DCPC) or GISC, when they have considered that the migration is complete for them and their users;
	* After migration to WIS2, there is no requirement to run a Message Switching System (MSS) to receive or send data from centres that have not made the transition. The centre will decide when and if it wishes to stop its MSS. It can also stop data dissemination to GTS.
	
**Principle 4**: New data (such as from the Global Basic Observing Network (GBON), or related to climate, hydrology and the cryosphere) will be exchanged solely on WIS2:
	
	* WIS2 is designed to enable Resolution 1 (Cg-Ext(2021)) – WMO Unified Policy for the International Exchange of Earth System Data (https://library.wmo.int/idviewer/57850/9[_World Meteorological Congress: Abridged Final Report of the Extraordinary Session_] (WMO-No. 1281)) and to support the WMO Global Basic Observing Network. The new data will be available on WIS2. A centre not having made the migration to WIS2 will not receive the new data. This data will not have GTS TTAAii headers and will not be exchanged over the GTS.
