== Temporary global services

=== GTS to WIS2 Gateway

The Executive Council, with resolution 34 (EC-76), endorsed the WMO Information System 2 (WIS2) implementation plan and recognized the importance of establishing a pilot phase to develop the WIS2 infrastructure and begin testing it in order to be ready for a preoperational phase in 2024, and then for the transition starting on 2025. According to the WIS2 implementation plan, the Global Telecommunication System (GTS) will be decommissioned by 2030, and National Meteorological and Hydrological Services NMHSs will use the WIS2 platform for data exchange.

During the transition period, in order to avoid some WIS centres being forced to run both data-sharing frameworks WIS2 and GTS simultaneously, with the challenges associated with maintaining two operational systems for the same purpose, a gateway from GTS to WIS2 is designed, taking into account the time required for Members to migrate to the new systems and minimizing the time a member has to operate both systems in parallel.

==== Purpose

The purpose of the GTS to WIS2 gateway is to enable Members who have migrated to WIS2 and have stopped their GTS systems to continue receiving GTS data from WIS2. This gateway also enables users who are not connected to GTS to access GTS data, during the transition phase, from WIS2. The GTS to WIS2 gateway will forward the GTS traffic it receives to WIS2. In accordance withn WIS2 specification, every data received on one GTS link will be stored on a HTTP(s) endpoint of the Gateway and will generate a WIS2 Notification Message. 

==== GTS to WIS2 Gateway provider

The purpose of the GTS to WIS2 gateway is to enable Members, having migrated to WIS2, to stop their GTS systems while continueing receiving GTS data via WIS2. In addition, this gateway function also enables users who are not connected to GTS to already obtain data originally published on the GTS. The function of GTS to WIS2 gateway is to forward all the GTS traffic received by the Member operating that service, to WIS2, so that data received on its Message Switching System (MSS) will be stored and made available via HTTP(S). A Notification Message is then generated. It is published using the centre-id name defined for this gateway.
 
==== Technical requirements

* A GTS to WIS2 gateway is a DCPC function. All requirements related to WIS2 Nodes are applicable. A GTS to WIS2 gateway will obtain from the WMO Secretariat a specific unique centre-id.
* In addition to the standard WIS2 Node specifications, the GTS to WIS2 gateway will support the following:
** The Topic Hierarchy for GTS data on WIS2 will be:
*** ``origin/a/wis2/{centre-id}/data/[core|recommended]/T1/T2/A1/A2/ii/CCCC``
*** e.g for DWD: ``origin/a/wis2/de-dwd-gts-to-wis2/data/[core|recommended]/T1/T2/A1/A2/ii/CCCC`` and for JMA: ``origin/a/wis2/jp-jma-gts-to-wis2/data/[core|recommended]/T1/T2/A1/A2/ii/CCCC``
** The ``T1/T2/A1/A2/ii/CCCC`` above is derived from the headers of the data received on the GTS.
* The Global Caches will cache data that is being published using ``core`` in the Topic Hierarchy.
* Data Consumers receiving the GTS data through WIS2 will need to be able to handle duplicates. This is consistent with the current practices of handling duplicate messages on the GTS.
* Access to recommended GTS data should be restricted to WMO members.

=== WIS2 to GTS Gateway

The WIS2 Implementation plan outlines a gradual transition of data exchange from the Global Telecommunications System (GTS) to WIS2. The transition is expected to occur between 2025 and 2030. The GTS will be decommissioned once the transition is complete.  

==== Purpose

Once a NMC centre, running a Message Switching System and exchanging data on the GTS, has implemented WIS2, it may want to stop sending its data directly on the GTS so that it can stop their MSS. 

The WIS2 to GTS gateway will ensure that *only the data currently available on the GTS* and whose Member is wishing to stop its Message Switching System (MSS) will be re-published onto the GTS, so that no data is loss during the transition. 

To ensure resilient operation, there will be more than one WIS2 to GTS Gateway.

==== WIS2 to GTS Gateway operators
The gateway will be provided by designated Regional Telecommunication Hubs (RTH). 

==== Technical requirements
===== For WIS Centres wishing to stop their MSS

. The GTS header CCCC code to be used for the bulletins published on their behalf.
. The list of GTS bulletins, and, where appropriate, their cut-off times, to be published by the Gateway on their behalf.
*Note* Issue #32 created on the last two points.

A Member planning to stop GTS transmission shall, in addition to WIS2 Node operations, and when publishing a WIS2 Notification Message for data that should also be available on the GTS shall indicate the GTS Abbreviated Header Line (AHL) of the bulletin in which the data is to be published. 

This is done by including the ``gts`` property in the WIS2 Notification Message (see example below). This enables the WIS2 to GTS Gateway operator to easily identify data for republication on the GTS and the AHL of the associated data.
  
[source,json]
-----
"properties": {
  …
  "gts": {
       "ttaaii": "FTAE31",
       "cccc": "VTBB"
  }
}
-----

===== For WIS2 to GTS Gateway operators
A WIS2 to GTS Gateway operator shall operate the following components throughout the transition period:

. A WIS2 Node to retrieve data published on WIS2. All WIS2 Node specifications apply to the WIS2 to GTS Gateway.
. A Message Switching System (MSS) with the required configuration to reach all RTHs.

The Gateway will: 

. Subscribe to notifications on the topic: ``+cache/a/wis2/{centre-id}/data/#+``, where ``{centre-id}`` refers to a WIS2 Node wishing to stop the native GTS function.

. Add the **CCCC** code designated by the Member to the Gateway's publication __whitelist__.
. Complete configuration required in the MSS for each bulletin specified by the Member; e.g., set up the data import channel, set the cut-off time, etc. 
*Note* See Issue #32

* To ensure resilient operation, the Gateway should subscribe to notification messages from multiple Global Brokers.
* During the transition period, other gateways will republish GTS data to WIS2. These __GTS to WIS2 Gateways__ will publish via a designated ``centre-id``. To avoid an infinite loop of republication, it is essential that a WIS2 to GTS Gateway **does not** subscribe to notification messages associated with a centre-id of a GTS to WIS2 Gateway.

For each WIS2 notification message received, the Gateway will:

. Parse the notification message, discarding it if:
.. The notification message is a duplicate.
.. The notification message refers to data that has already been republished by the Gateway.
.. The notification message does not include the ``gts`` property.
.. The value of the ``cccc`` property is not on the Gateway's publication whitelist.
. If the notification message was not discarded, then:
.. Parse the notification message to extract the **TTAAii** and **CCCC** which identifies the bulletin that the data should be published within.
.. Download the data indicated in the message, using the __canonical__ link if one is specified.
.. Pass the downloaded data file to the Gateway's MSS via the channel configured for the bulletin (**TTAAii**, **CCCC**). 

**Note**: the WIS2 to GTS Gateway should report events, following the agreed procedure.

The Gateway's MSS will process incoming data files, batching individual items into bulletins as per configuration, and publish those bulletins onto the GTS for onward distributed via RTHs on the MTN and beyond.

The Gateway's MSS will publish bulletin amendments / corrections where data arrives after the cut-off time.
*Note* See Issue #32

== Stopping a Message Switching System

Thanks to the gateway functions described in previous chapter, WIS Centers currently using the GTS to exchange operational data, after having successfully implementing a WIS2 Node with the additional features required for the gateways to provide the gateway service, will be able to stop their Message Switching System, if they wish to do so, before the end of the complete migration.
Gradually stopping all the MSS shall be done in an orderly and coordinated manner so that all data required by Members for their operations will continue to be available.

"Management of WIS1 and GTS" part of this Transition Guide recalls the various roles on the GTS (NMC, RTH, WMC). It also details when a Center can stop its MSS. When all the conditions for a Centre are met, the following decommissioning procedure can be applied.

TODO: Include stopping MSS sequence diagram

The sequence diagram details the list of actions required and the role of the various entities involved in this action.
The responsible GISC for the WIS Center will have a key role to play. The GISC will have to ensure that the WIS Center has properly implemented the requirements and that the procedure is well understood by the WIS Center so that, no data is lost during the transition.
WMO secretariat will act as the coordination body between all parties.
It is crucial that all parties are strictly following the agreed procedure.

It must also be noted that the final switch (stopping the MSS by the WIS Center and activating the gateway function for the data of the WIS Center) should happen at the same moment. The exact time and date will be chosen by the various parties under the control of WMO Secretariat.

