==  WIS2 to GTS Gateway

=== Purpose

Once a WIS centre has migrated from GTS to WIS2, and as defined in `How to stop the MSS ?`, a centre may want to stop sending it data directly on the GTS.
The WIS2 to GTS gateway will ensure that *the data currently available on the GTS* (and only this) and whose provider is wishing to stop its Message Switching System (MSS) will be re-published onto the GTS. 

To ensure resilient operation there will be more than one WIS2 to GTS Gateway.

=== WIS2 to GTS Gateway operators
The gateway will be provided by volunteering, and then approved, Regional Telecommunication Hubs (RTH).

=== Technical requirements

==== For WIS Centres wishing to stop their MSS

When publishing a WIS2 Notification Message for data that should also be available on the GTS, the WIS Centre shall indicate the GTS Abbreviated Header Line (AHL) of the bulletin in which the data is to be published. 

This is done by including the ``gts`` property in the WIS2 Notification Message (see example below). This enables the WIS2 to GTS Gateway operator to easily identify data for republication on the GTS and the AHL of the associated data.
  
[source,json]
-----
"properties": {
  …
  "gts": {
       "ttaaii": "FTAE31",
       "cccc": "VTBB"
  }
}
-----

==== For WIS2 to GTS Gateway operators
A WIS2 to GTS Gateway operator shall operate the following components throughout the transition period:

. A WIS2 Node to retrieve data published on WIS2. All WIS2 Node specifications apply to the WIS2 to GTS Gateway.
. A Message Switching System (MSS) with the required configuration to reach all RTHs.

The Gateway will: 

. Subscribe to notifications on the topic: ``+cache/a/wis2/{centre-id}/data/core/#+``, where ``{centre-id}`` refers to a WIS2 Node wishing to stop the native GTS function.

** Comments by Rémy: Not sure what to do with the below
. Add the **CCCC** code designated by the Member to the Gateway's publication __whitelist__.
. Complete configuration required in the MSS for each bulletin specified by the Member; e.g., set up the data import channel, set the cut-off time, etc. 

* To ensure resilient operation, the Gateway should subscribe to notification messages from multiple Global Brokers.
* During the transition period, other gateways will republish GTS data to WIS2. These __GTS to WIS2 Gateways__ will publish via a designated ``centre-id``. To avoid an infinite loop of republication, it is essential that a WIS2 to GTS Gateway **does not** subscribe to notification messages associated with a centre-id of a GTS to WIS2 Gateway.

For each WIS2 notification message received, the Gateway will:

. Parse the notification message, discarding it if:
.. The notification message is a duplicate.
.. The notification message refers to data that has already been republished by the Gateway.
.. The notification message does not include the ``gts`` property.
.. The value of the ``cccc`` property is not on the Gateway's publication whitelist.
. If the notification message was not discarded, then:
.. Parse the notification message to extract the **TTAAii** and **CCCC** which identifies the bulletin that the data should be published within.
.. Download the data indicated in the message, using the __canonical__ link if one is specified.
.. Pass the downloaded data file to the Gateway's MSS via the channel configured for the bulletin (**TTAAii**, **CCCC**). 

**Note**: the WIS2 to GTS Gateway should log and report failures. [TODO: elaborate on failure reporting]

The Gateway's MSS will process incoming data files, batching individual items into bulletins as per configuration, and publish those bulletins onto the GTS for onward distributed via RTHs on the MTN and beyond.

The Gateway's MSS will publish bulletin amendments / corrections where data arrives after the cut-off time.

