name: WIS2 Transition Guide

on:
  push:
    branches:
    - main
    paths:
    - 'transition-guide/**'

env:
  FILE_BASENAME: wis2-transition-guide-APPROVED

jobs:
  build-wis2-transition-guide:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y \
          && sudo apt-get install -y pandoc \
          && sudo gem install asciidoctor asciidoctor-pdf
      - name: checkout repository
        uses: actions/checkout@v3
      - name: build documentation
        run: |
          mkdir -p /tmp/wis2-transition-guide/transition-guide/images \
          && cd transition-guide \
          && asciidoctor --trace -o /tmp/wis2-transition-guide/transition-guide/${FILE_BASENAME}.html index.adoc \
          && asciidoctor --trace --backend docbook --out-file - index.adoc | pandoc --from docbook --to docx --output /tmp/wis2-transition-guide/transition-guide/${FILE_BASENAME}.docx \
          && asciidoctor --trace -r asciidoctor-pdf --trace -b pdf -o /tmp/wis2-transition-guide/transition-guide/${FILE_BASENAME}.pdf index.adoc \
          && cp images/*.png /tmp/wis2-transition-guide/transition-guide/images \
          && cd ..
      - name: checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: update gh-pages branch and publish
        run: | 
          git checkout gh-pages
          git config --global user.email "tomkralidis@gmail.com"
          git config --global user.name "Tom Kralidis"
          rm -rf transition-guide
          mv -f /tmp/wis2-transition-guide/* .
          git add .
          git commit -am "update WIS2 Guide build"
          git push

